"""empty message

Revision ID: 0b9c940a7896
Revises: 1259a9469ddb
Create Date: 2022-03-31 15:27:04.728492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9c940a7896'
down_revision = '1259a9469ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
