"""empty message

Revision ID: 2ac1485f3526
Revises: e052247a4800
Create Date: 2022-04-28 09:36:51.052829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ac1485f3526'
down_revision = 'e052247a4800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipAddresses', sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('settings', sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('subnets', 'dateCreated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('vlans', sa.Column('dateCreated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vlans', 'dateCreated')
    op.alter_column('subnets', 'dateCreated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('settings', 'dateCreated')
    op.drop_column('ipAddresses', 'dateCreated')
    # ### end Alembic commands ###
