"""empty message

Revision ID: 2d349a41c657
Revises: aecfd0880309
Create Date: 2022-04-27 19:09:30.591899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d349a41c657'
down_revision = 'aecfd0880309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
