"""empty message

Revision ID: 3d117ede7e63
Revises: 81d27bf360ed
Create Date: 2022-04-28 09:46:25.747979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d117ede7e63'
down_revision = '81d27bf360ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
