"""empty message

Revision ID: 81d27bf360ed
Revises: 2ac1485f3526
Create Date: 2022-04-28 09:45:15.128350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d27bf360ed'
down_revision = '2ac1485f3526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
