"""empty message

Revision ID: afc9193d5664
Revises: cc4e4fce0c6d
Create Date: 2022-04-28 08:51:12.206146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc9193d5664'
down_revision = 'cc4e4fce0c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
