"""empty message

Revision ID: cc4e4fce0c6d
Revises: b3b95c391e69
Create Date: 2022-04-27 20:00:35.851506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4e4fce0c6d'
down_revision = 'b3b95c391e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
