"""empty message

Revision ID: b30bd1bfc37d
Revises: 
Create Date: 2021-09-05 22:18:11.407434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b30bd1bfc37d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ipAddresses', sa.Column('dateLastSeen', sa.DateTime(), nullable=True))
    op.add_column('ipAddresses', sa.Column('dateLastEdited', sa.DateTime(), nullable=True))
    op.alter_column('ipAddresses', 'state_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'ipAddresses', 'addressStates', ['state_id'], ['id'])
    op.drop_column('ipAddresses', 'lastSeen')
    op.add_column('subnets', sa.Column('masterSubnet_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('subnets', sa.Column('vlan_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('subnets', sa.Column('allowRequests', sa.Boolean(), nullable=False))
    op.add_column('subnets', sa.Column('dateLastEdited', sa.DateTime(), nullable=True))
    op.add_column('subnets', sa.Column('dateLastScanned', sa.DateTime(), nullable=True))
    op.add_column('subnets', sa.Column('dateLastDiscovered', sa.DateTime(), nullable=True))
    op.add_column('subnets', sa.Column('doDiscovery', sa.Boolean(), nullable=True))
    op.add_column('subnets', sa.Column('doScan', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'subnets', 'subnets', ['masterSubnet_id'], ['id'])
    op.create_foreign_key(None, 'subnets', 'vlans', ['vlan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subnets', type_='foreignkey')
    op.drop_constraint(None, 'subnets', type_='foreignkey')
    op.drop_column('subnets', 'doScan')
    op.drop_column('subnets', 'doDiscovery')
    op.drop_column('subnets', 'dateLastDiscovered')
    op.drop_column('subnets', 'dateLastScanned')
    op.drop_column('subnets', 'dateLastEdited')
    op.drop_column('subnets', 'allowRequests')
    op.drop_column('subnets', 'vlan_id')
    op.drop_column('subnets', 'masterSubnet_id')
    op.add_column('ipAddresses', sa.Column('lastSeen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ipAddresses', type_='foreignkey')
    op.alter_column('ipAddresses', 'state_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_column('ipAddresses', 'dateLastEdited')
    op.drop_column('ipAddresses', 'dateLastSeen')
    # ### end Alembic commands ###
