# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbaccess.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x62\x61\x63\x63\x65ss.proto\"Z\n\nreadFilter\x12\x12\n\ncolumnName\x18\x01 \x01(\t\x12#\n\x0f\x66ilterOperation\x18\x02 \x01(\x0e\x32\n.filterOps\x12\x13\n\x0b\x66ilterValue\x18\x03 \x01(\t\"2\n\x0cwriteMessage\x12\x11\n\ttablename\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\x0c\"Q\n\rwriteResponse\x12\x15\n\rreturnMessage\x18\x01 \x01(\x0c\x12\x12\n\nstatusCode\x18\x02 \x01(\x05\x12\x15\n\rstatusMessage\x18\x04 \x01(\t\"A\n\x0breadMessage\x12\x11\n\ttablename\x18\x01 \x01(\t\x12\x1f\n\nreadFilter\x18\x02 \x03(\x0b\x32\x0b.readFilter\"P\n\x0creadResponse\x12\x15\n\rreturnMessage\x18\x01 \x01(\x0c\x12\x12\n\nstatusCode\x18\x02 \x01(\x05\x12\x15\n\rstatusMessage\x18\x03 \x01(\t\".\n\rdeleteMessage\x12\x11\n\ttableName\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\";\n\x0e\x64\x65leteResponse\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x15\n\rstatusMessage\x18\x02 \x01(\t\"E\n\rupdateMessage\x12\x11\n\ttableName\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x15\n\rupdateMessage\x18\x03 \x01(\x0c\"R\n\x0eupdateResponse\x12\x15\n\rreturnMessage\x18\x01 \x01(\x0c\x12\x12\n\nstatusCode\x18\x02 \x01(\x05\x12\x15\n\rstatusMessage\x18\x04 \x01(\t*1\n\tfilterOps\x12\n\n\x06\x45QUALS\x10\x00\x12\x08\n\x04LIKE\x10\x01\x12\x0e\n\nLIKE_REGEX\x10\x02\x32\x8a\x02\n\x08\x44\x42\x41\x63\x63\x65ss\x12/\n\x0ewriteIpAddress\x12\r.writeMessage\x1a\x0e.writeResponse\x12\x30\n\x0fwriteRowToTable\x12\r.writeMessage\x1a\x0e.writeResponse\x12/\n\x10readRowFromTable\x12\x0c.readMessage\x1a\r.readResponse\x12\x33\n\x10updateRowInTable\x12\x0e.updateMessage\x1a\x0f.updateResponse\x12\x35\n\x12\x64\x65leteRowFromTable\x12\x0e.deleteMessage\x1a\x0f.deleteResponseb\x06proto3')

_FILTEROPS = DESCRIPTOR.enum_types_by_name['filterOps']
filterOps = enum_type_wrapper.EnumTypeWrapper(_FILTEROPS)
EQUALS = 0
LIKE = 1
LIKE_REGEX = 2


_READFILTER = DESCRIPTOR.message_types_by_name['readFilter']
_WRITEMESSAGE = DESCRIPTOR.message_types_by_name['writeMessage']
_WRITERESPONSE = DESCRIPTOR.message_types_by_name['writeResponse']
_READMESSAGE = DESCRIPTOR.message_types_by_name['readMessage']
_READRESPONSE = DESCRIPTOR.message_types_by_name['readResponse']
_DELETEMESSAGE = DESCRIPTOR.message_types_by_name['deleteMessage']
_DELETERESPONSE = DESCRIPTOR.message_types_by_name['deleteResponse']
_UPDATEMESSAGE = DESCRIPTOR.message_types_by_name['updateMessage']
_UPDATERESPONSE = DESCRIPTOR.message_types_by_name['updateResponse']
readFilter = _reflection.GeneratedProtocolMessageType('readFilter', (_message.Message,), {
  'DESCRIPTOR' : _READFILTER,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:readFilter)
  })
_sym_db.RegisterMessage(readFilter)

writeMessage = _reflection.GeneratedProtocolMessageType('writeMessage', (_message.Message,), {
  'DESCRIPTOR' : _WRITEMESSAGE,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:writeMessage)
  })
_sym_db.RegisterMessage(writeMessage)

writeResponse = _reflection.GeneratedProtocolMessageType('writeResponse', (_message.Message,), {
  'DESCRIPTOR' : _WRITERESPONSE,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:writeResponse)
  })
_sym_db.RegisterMessage(writeResponse)

readMessage = _reflection.GeneratedProtocolMessageType('readMessage', (_message.Message,), {
  'DESCRIPTOR' : _READMESSAGE,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:readMessage)
  })
_sym_db.RegisterMessage(readMessage)

readResponse = _reflection.GeneratedProtocolMessageType('readResponse', (_message.Message,), {
  'DESCRIPTOR' : _READRESPONSE,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:readResponse)
  })
_sym_db.RegisterMessage(readResponse)

deleteMessage = _reflection.GeneratedProtocolMessageType('deleteMessage', (_message.Message,), {
  'DESCRIPTOR' : _DELETEMESSAGE,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:deleteMessage)
  })
_sym_db.RegisterMessage(deleteMessage)

deleteResponse = _reflection.GeneratedProtocolMessageType('deleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETERESPONSE,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:deleteResponse)
  })
_sym_db.RegisterMessage(deleteResponse)

updateMessage = _reflection.GeneratedProtocolMessageType('updateMessage', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEMESSAGE,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:updateMessage)
  })
_sym_db.RegisterMessage(updateMessage)

updateResponse = _reflection.GeneratedProtocolMessageType('updateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:updateResponse)
  })
_sym_db.RegisterMessage(updateResponse)

_DBACCESS = DESCRIPTOR.services_by_name['DBAccess']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILTEROPS._serialized_start=658
  _FILTEROPS._serialized_end=707
  _READFILTER._serialized_start=18
  _READFILTER._serialized_end=108
  _WRITEMESSAGE._serialized_start=110
  _WRITEMESSAGE._serialized_end=160
  _WRITERESPONSE._serialized_start=162
  _WRITERESPONSE._serialized_end=243
  _READMESSAGE._serialized_start=245
  _READMESSAGE._serialized_end=310
  _READRESPONSE._serialized_start=312
  _READRESPONSE._serialized_end=392
  _DELETEMESSAGE._serialized_start=394
  _DELETEMESSAGE._serialized_end=440
  _DELETERESPONSE._serialized_start=442
  _DELETERESPONSE._serialized_end=501
  _UPDATEMESSAGE._serialized_start=503
  _UPDATEMESSAGE._serialized_end=572
  _UPDATERESPONSE._serialized_start=574
  _UPDATERESPONSE._serialized_end=656
  _DBACCESS._serialized_start=710
  _DBACCESS._serialized_end=976
# @@protoc_insertion_point(module_scope)
