# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbaccess.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x62\x61\x63\x63\x65ss.proto\"`\n\x0cobjIpAddress\x12\x14\n\x0cstrIpAddress\x18\x01 \x01(\t\x12\x12\n\nsubnetMask\x18\x02 \x01(\t\x12\x0e\n\x06prefix\x18\x03 \x01(\t\x12\x16\n\x0e\x64\x65\x66\x61ultGateway\x18\x04 \x01(\t\"!\n\rwriteResponse\x12\x10\n\x08response\x18\x01 \x01(\t2;\n\x08\x44\x42\x41\x63\x63\x65ss\x12/\n\x0ewriteIpAddress\x12\r.objIpAddress\x1a\x0e.writeResponseb\x06proto3')



_OBJIPADDRESS = DESCRIPTOR.message_types_by_name['objIpAddress']
_WRITERESPONSE = DESCRIPTOR.message_types_by_name['writeResponse']
objIpAddress = _reflection.GeneratedProtocolMessageType('objIpAddress', (_message.Message,), {
  'DESCRIPTOR' : _OBJIPADDRESS,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:objIpAddress)
  })
_sym_db.RegisterMessage(objIpAddress)

writeResponse = _reflection.GeneratedProtocolMessageType('writeResponse', (_message.Message,), {
  'DESCRIPTOR' : _WRITERESPONSE,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:writeResponse)
  })
_sym_db.RegisterMessage(writeResponse)

_DBACCESS = DESCRIPTOR.services_by_name['DBAccess']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJIPADDRESS._serialized_start=18
  _OBJIPADDRESS._serialized_end=114
  _WRITERESPONSE._serialized_start=116
  _WRITERESPONSE._serialized_end=149
  _DBACCESS._serialized_start=151
  _DBACCESS._serialized_end=210
# @@protoc_insertion_point(module_scope)
