# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbaccess.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dbaccess.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x64\x62\x61\x63\x63\x65ss.proto\"`\n\x0cobjIpAddress\x12\x14\n\x0cstrIpAddress\x18\x01 \x01(\t\x12\x12\n\nsubnetMask\x18\x02 \x01(\t\x12\x0e\n\x06prefix\x18\x03 \x01(\t\x12\x16\n\x0e\x64\x65\x66\x61ultGateway\x18\x04 \x01(\t\"!\n\rwriteResponse\x12\x10\n\x08response\x18\x01 \x01(\t2;\n\x08\x44\x42\x41\x63\x63\x65ss\x12/\n\x0ewriteIpAddress\x12\r.objIpAddress\x1a\x0e.writeResponseb\x06proto3'
)




_OBJIPADDRESS = _descriptor.Descriptor(
  name='objIpAddress',
  full_name='objIpAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strIpAddress', full_name='objIpAddress.strIpAddress', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subnetMask', full_name='objIpAddress.subnetMask', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='objIpAddress.prefix', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='defaultGateway', full_name='objIpAddress.defaultGateway', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=114,
)


_WRITERESPONSE = _descriptor.Descriptor(
  name='writeResponse',
  full_name='writeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='writeResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['objIpAddress'] = _OBJIPADDRESS
DESCRIPTOR.message_types_by_name['writeResponse'] = _WRITERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

objIpAddress = _reflection.GeneratedProtocolMessageType('objIpAddress', (_message.Message,), {
  'DESCRIPTOR' : _OBJIPADDRESS,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:objIpAddress)
  })
_sym_db.RegisterMessage(objIpAddress)

writeResponse = _reflection.GeneratedProtocolMessageType('writeResponse', (_message.Message,), {
  'DESCRIPTOR' : _WRITERESPONSE,
  '__module__' : 'dbaccess_pb2'
  # @@protoc_insertion_point(class_scope:writeResponse)
  })
_sym_db.RegisterMessage(writeResponse)



_DBACCESS = _descriptor.ServiceDescriptor(
  name='DBAccess',
  full_name='DBAccess',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=151,
  serialized_end=210,
  methods=[
  _descriptor.MethodDescriptor(
    name='writeIpAddress',
    full_name='DBAccess.writeIpAddress',
    index=0,
    containing_service=None,
    input_type=_OBJIPADDRESS,
    output_type=_WRITERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DBACCESS)

DESCRIPTOR.services_by_name['DBAccess'] = _DBACCESS

# @@protoc_insertion_point(module_scope)
